version: "3.8"

services:
  sapiens:
    build: .
    container_name: sapiens
    restart: unless-stopped

    environment:
      - UDP_PORT=16161
      - PUBLIC_MODE=true
      - BUGREPORT_OPTIN=true

    ports:
      - "16161:16161/udp"

    volumes:
      - sapiens_data:/root/.local/share/majicjungle/sapiens

    tty: true
    stdin_open: true

volumes:
  sapiens_data:
